# Generated by Django 5.1.4 on 2025-01-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_banner_post_image_post_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/fallback.png', upload_to='images/'),
        ),
    ]
