# Generated by Django 5.1.4 on 2025-01-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='fallback.png', upload_to=''),
        ),
    ]
